// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using terentevalexandrKt_31_20.Database;

#nullable disable

namespace terentevalexandrKt_31_20.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240111224501_CreateDatabase")]
    partial class CreateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("terentevalexandrKt_31_20.Models.EducationalSubject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasComment("Идентификатор дисциплины");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar")
                        .HasColumnName("name")
                        .HasComment("Наименование дисциплины");

                    b.HasKey("Id")
                        .HasName("pk_educationalsubject_id");

                    b.ToTable("educationalsubject", (string)null);
                });

            modelBuilder.Entity("terentevalexandrKt_31_20.Models.Professor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasComment("Идентификатор преподавателя");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar")
                        .HasColumnName("firstname")
                        .HasComment("Имя преподавателя");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar")
                        .HasColumnName("lastname")
                        .HasComment("Фамилия преподавателя");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar")
                        .HasColumnName("middlename")
                        .HasComment("Отчество преподавателя");

                    b.HasKey("Id")
                        .HasName("pk_professor_id");

                    b.ToTable("professor", (string)null);
                });

            modelBuilder.Entity("terentevalexandrKt_31_20.Models.Workload", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasComment("Идентификатор нагрузки");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EducationalSubjectId")
                        .HasColumnType("int")
                        .HasColumnName("educationsubject_id")
                        .HasComment("Идентификатор дисциплины");

                    b.Property<int>("NumberOfHours")
                        .HasColumnType("int")
                        .HasColumnName("numberofhours")
                        .HasComment("Количество часов нагрузки");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("int")
                        .HasColumnName("professor_id")
                        .HasComment("Идентификатор профессора");

                    b.HasKey("Id")
                        .HasName("pk_workload_id");

                    b.HasIndex("EducationalSubjectId");

                    b.HasIndex("ProfessorId");

                    b.ToTable("workload", (string)null);
                });

            modelBuilder.Entity("terentevalexandrKt_31_20.Models.Workload", b =>
                {
                    b.HasOne("terentevalexandrKt_31_20.Models.EducationalSubject", "EducationalSubject")
                        .WithMany()
                        .HasForeignKey("EducationalSubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_f_educationalsubject_id");

                    b.HasOne("terentevalexandrKt_31_20.Models.Professor", "Professor")
                        .WithMany()
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_f_professor_id");

                    b.Navigation("EducationalSubject");

                    b.Navigation("Professor");
                });
#pragma warning restore 612, 618
        }
    }
}
